# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/AshleighAndJohn/AshleighAndJohn.github.io
title: Ashleigh and John Matrimonial Extravaganza
email: labaumgardner@gmail.com
author: Ashleigh Baumgardner and John Benner
description: Homepage for Ashleigh and John wedding
copyright: ''
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
collections:
  - sections
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    text: Blog
    url: http://chugly.github.io/
  - title: spotify
    text: Playlist
    url: https://open.spotify.com/user/126045799/playlist/1KnnWPmEOm3PiQ93mpAQuF

